// https://docs.renovatebot.com/self-hosted-configuration/
module.exports = {
  branchPrefix: 'repo-stream-renovate/',
  dryRun: false,
  username: 'renovate-release',
  gitAuthor: 'Renovate Bot <bot@renovateapp.com>',
  onboarding: false,
  platform: 'github',
  autodiscover: false,
  requireConfig: false,
  logLevel: 'debug',
  forkMode: true,
  forkToken: process.env.RENOVATE_TOKEN,
  //autodiscoverFilter: "mondeja/*",
  //includeForks: false,
  repositories: [
    "mondeja/actix-react-starter-template",
    "mondeja/compile-time-create-file",
    "mondeja/cartocss-doc-parser",
    "mondeja/django-svelte-start",
    "mondeja/http-request-codegen",
    /*"mondeja/hunspellcheck",
    "mondeja/inkscape-braille-l18n-ext",
    "mondeja/mdpo",
    "mondeja/mkdocs-include-markdown-plugin",
    "mondeja/mkdocs-material-relative-language-selector",
    "mondeja/mkdocs-mdpo-plugin",
    "mondeja/mondeja",
    "mondeja/pgdoc-datatype-parser",
    "mondeja/potojson",
    "mondeja/pr-linked-issues-action",
    "mondeja/pre-commit-hooks",
    "mondeja/pre-commit-po-hooks",
    "mondeja/pytest-blender",
    "mondeja/remove-labels-gh-action",
    "mondeja/repo-stream",
    "mondeja/repo-stream-config",
    "mondeja/sdown",
    "mondeja/shread",
    "mondeja/siglo25",
    "mondeja/simple-icons-blender",
    "mondeja/simple-icons-drawio",
    "mondeja/solaris-vm-action",
    "mondeja/svg-path-bbox",
    "mondeja/svg-path-segments",
    "mondeja/waves",
    "mondeja/woff2otf",*/
  ],
};