name: Renovate
on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Renovate
        uses: renovatebot/github-action@v28.25.2
        env:
          RENOVATE_CONFIG_FILE: renovate-config.js
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
