name: repo-stream update

on:
  schedule:
    - cron: 0 4 1/7 * *
  workflow_dispatch:

jobs:
  repo-stream-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install repo-stream
        run: pip install repo-stream
      - name: Configure GIT
        run: |
          git config --global user.email "mondejar1994@gmail.com"
          git config --global user.name "Álvaro Mondéjar"
      - name: Run repo-stream
        uses: mondeja/repo-stream@v1.3.0
        with:
          usernames: mondeja
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_USERNAME: mondeja
